import { NextConfig } from 'next';
const { routing } = require("./i18n/routing");
const withNextIntl = require("next-intl/plugin")(routing);

/**
 * Interface representing the structure of a redirect rule.
 * Next.js internal 'Redirect' type is more complex, so we define 
 * our local requirement here.
 */
interface RedirectRule {
  source: string;
  destination: string;
  permanent: boolean;
}

// Explicitly type the array to prevent 'any[]' inference errors
let generatedRedirects: RedirectRule[] = [];

try {
  // Use require for the CommonJS generated file
  const loadedRedirects = require("./redirects.generated.cjs");

  if (Array.isArray(loadedRedirects)) {
    generatedRedirects = loadedRedirects as RedirectRule[];
  }
} catch (e) {
  generatedRedirects = [];
}

// Example-ID legacy redirects: 301s from old "-zh-" / "-en-" example
// IDs to their current canonical equivalents. Generated by
// scripts/generate_example_id_redirects.cjs from GSC noindex exports.
let generatedExampleRedirects: RedirectRule[] = [];
try {
  const loadedExampleRedirects = require("./redirects.examples.generated.cjs");
  if (Array.isArray(loadedExampleRedirects)) {
    generatedExampleRedirects = loadedExampleRedirects as RedirectRule[];
  }
} catch {
  generatedExampleRedirects = [];
}

const nextConfig: NextConfig = {
  reactStrictMode: true,

  eslint: { 
    ignoreDuringBuilds: true 
  },

  trailingSlash: false,
  skipTrailingSlashRedirect: true,

  experimental: {
    serverActions: { 
      allowedOrigins: ["*"] 
    },
  },

  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'lh3.googleusercontent.com' },
      { protocol: 'https', hostname: 'cdn.curify-ai.com' },
      { protocol: 'https', hostname: 'videotranslatetest.blob.core.windows.net' },
      { protocol: 'https', hostname: 'pbs.twimg.com' },
      { protocol: 'https', hostname: 'storage.googleapis.com' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
    ],
  },

  async redirects() {
    const LOCALE_RE = routing.locales.join("|");

    const manualRedirects: RedirectRule[] = [
      {
        source: "/bilingual-subtitles",
        destination: "/tools/bilingual-subtitles",
        permanent: true,
      },
      {
        source: "/video-dubbing",
        destination: "/tools/video-dubbing",
        permanent: true,
      },
      {
        source: `/:locale(${LOCALE_RE})/bilingual-subtitles`,
        destination: "/:locale/tools/bilingual-subtitles",
        permanent: true,
      },
      {
        source: `/:locale(${LOCALE_RE})/video-dubbing`,
        destination: "/:locale/tools/video-dubbing",
        permanent: true,
      },
      {
        source: "/en/tools/:path*",
        destination: "/tools/:path*",
        permanent: true,
      },
      {
        source: "/nano-template/world-travel-map-illustration-en",
        destination: "/nano-template/world-travel-map-illustration",
        permanent: true,
      },
      {
        source: `/:locale(${LOCALE_RE})/nano-template/world-travel-map-illustration-en`,
        destination: "/:locale/nano-template/world-travel-map-illustration",
        permanent: true,
      },

      // Legacy marketing routes that surfaced in the GSC 404 report.
      // Each maps to the closest current equivalent so the SEO signal
      // moves forward instead of dead-ending or soft-404'ing.
      { source: "/gallery", destination: "/nano-banana-pro-prompts", permanent: true },
      { source: `/:locale(${LOCALE_RE})/gallery`, destination: "/:locale/nano-banana-pro-prompts", permanent: true },
      { source: "/generate", destination: "/nano-banana-pro-prompts", permanent: true },
      { source: `/:locale(${LOCALE_RE})/generate`, destination: "/:locale/nano-banana-pro-prompts", permanent: true },
      { source: "/templates", destination: "/nano-banana-pro-prompts", permanent: true },
      { source: `/:locale(${LOCALE_RE})/templates`, destination: "/:locale/nano-banana-pro-prompts", permanent: true },
      { source: "/subtitle-generator", destination: "/tools/bilingual-subtitles", permanent: true },
      { source: `/:locale(${LOCALE_RE})/subtitle-generator`, destination: "/:locale/tools/bilingual-subtitles", permanent: true },
      { source: "/video-translator", destination: "/tools/video-dubbing", permanent: true },
      { source: `/:locale(${LOCALE_RE})/video-translator`, destination: "/:locale/tools/video-dubbing", permanent: true },
    ];

    const isValid = (r: unknown): r is RedirectRule =>
      !!r &&
      typeof (r as RedirectRule).source === "string" &&
      typeof (r as RedirectRule).destination === "string" &&
      typeof (r as RedirectRule).permanent === "boolean" &&
      (r as RedirectRule).source !== (r as RedirectRule).destination;

    const safeGeneratedRedirects = generatedRedirects.filter(isValid);
    const safeExampleRedirects = generatedExampleRedirects.filter(isValid);

    return [
      ...manualRedirects,
      ...safeGeneratedRedirects,
      ...safeExampleRedirects,
    ];
  },

  async headers() {
    const commonHeaders = [
      {
        key: "Cross-Origin-Opener-Policy",
        value: "same-origin-allow-popups",
      },
      {
        key: "Cross-Origin-Embedder-Policy",
        value: "unsafe-none",
      },
    ];

    return [
      {
        source: "/:path*",
        headers: commonHeaders,
      },
      {
        source: "/_next/:path*",
        headers: commonHeaders,
      },
      {
        source: "/api/:path*",
        headers: commonHeaders,
      },
    ];
  },
};

// Use ES Module export for .ts files
export default withNextIntl(nextConfig);