import blogsData from "@/public/data/blogs.json";

// Helper function to map blog data to the expected format
export function createBlogPostsConfig() {
  const blogPosts: Record<string, any> = {};
  
  blogsData.forEach((blog) => {
    const slug = blog.slug;
    
    // Determine namespace based on slug pattern
    let namespace = slug.replace(/-/g, '');
    
    // Special cases for namespace mapping
    const namespaceMap: Record<string, string> = {
      'aiPlatform': 'aiPlatform',
      'QA_Bot_to_Task': 'qaBotToTask',
      'age_AI': 'ageAi',
      'storyboard-labeling': 'storyboardLabeling',
      'video-enhancement': 'videoEnhancement',
      'video-evaluation': 'videoEvaluation',
      'storyboard-to-pipeline': 'storyboardToPipeline',
      'agents-vs-workflows': 'agentsVsWorkflows',
      'ae-vs-comfyui': 'aeVsComfyui',
      'translate-youtube-video': 'translateYoutubevideo',
      'translate-youtube-video-to-english': 'translateYoutubeVideoToEnglish',
      'ai-youtube-video-translator': 'aiYoutubeVideoTranslator',
      'what-is-voice-cloning': 'whatIsVoiceCloning',
      'voice-cloning-tools': 'voiceCloningTools',
      'f5-tts-voice-cloning': 'f5TtsVoiceCloning',
      'asl-video-translator': 'aslVideoTranslator',
      'how-to-translate-asl-video': 'howToTranslateAslVideo',
      'chinese-herbal-medicine-visual-guide': 'chineseHerbalMedicineVisualGuide',
      'evolution-timelines-visualization': 'evolutionTimelinesVisualization',
      'chinese-costume-history-infographic': 'chineseCostumeHistoryInfographic',
      'creative-ai-tools-websites': 'creativeAiToolsWebsites',
      'nano-banana-prompt-ecosystem': 'nanoBananaPromptEcosystem',
      'video-transcription-business-guide': 'videoTranscriptionBusinessGuide',
      'video-transcription-technical-deep-dive': 'videoTranscriptionTechnicalDeepDive',
      '10-prompting-tips-nano-banana': 'tenPromptingTipsNanoBanana',
      'curify-nano-banana-template-tips': 'curifyNanoBananaTemplateTips',
      '10-prompting-tips-video-generation': 'tenPromptingTipsVideoGeneration',
      'image-generation-model-comparison': 'imageGenerationModelComparison',
      'lip-sync-business-guide': 'lipSyncBusinessGuide',
      'lip-sync-technical-deep-dive': 'lipSyncTechnicalDeepDive',
      'character-prompt-generator': 'characterPromptGenerator',
      'mbti-character-generator': 'mbtiCharacterGenerator',
      'footballer-mbti-types': 'footballerMbtiTypes',
      'video-to-learning-pack': 'videoToLearningPack',
      'url-to-product-video': 'urlToProductVideo',
      'content-tagging-system': 'contentTaggingSystem',
      'visual-learning-tools': 'visualLearningTools',
      'ai-content-distribution-system': 'aiContentDistributionSystem',
      'ai-content-production-system': 'aiContentProductionSystem',
      'what-is-infographics': 'whatIsInfographics',
      'image-to-narrative-video': 'imageToNarrativeVideo',
      'series-infographic-vs-notebooklm': 'seriesInfographicVsNotebookLM',
      'ai-faceless-channel-pipeline': 'aifacelesschannelpipeline',
      'bilingual-ai-flashcards-early-childhood-education': 'bilingual-ai-flashcards-early-childhood-education',
      'ugcVideoTranslationScalingTiktoksShortsGlobalMarkets': 'ugcVideoTranslationScalingTiktoksShortsGlobalMarkets',
      'ai-collage-digital-wallpaper-guide': 'aiCollageDigitalWallpaperGuide',
      'weird-science-facts-classroom-engagement': 'weirdScienceFactsClassroomEngagement',
      'mbti-relationship-style-visualizer': 'mbtiRelationshipStyleVisualizer',
      'ai-reshaping-data-workflow': 'aiReshapingDataWorkflow',
      'ml-engineer-vs-ai-engineer': 'mlEngineerVsAiEngineer',
      'ai-engineering-hard-truth': 'aiEngineeringHardTruth',
      'ai-content-factory-for-agencies': 'aiContentFactoryForAgencies',
      'industrial-ai-for-illustrator-ip': 'industrialAiForIllustratorIp',
      'surtex-licensing-playbook-surface-designers': 'surtexLicensingPlaybookSurfaceDesigners',
      'ip-merch-design-ai-workflow': 'ipMerchDesignAiWorkflow',
      'ai-sticker-design-guide': 'aiStickerDesignGuide',
      'ai-die-cut-sticker-design': 'aiDieCutStickerDesign',
      'ai-packaging-design-guide': 'aiPackagingDesignGuide',
      'ai-makeover-templates': 'aiMakeoverTemplates',
      'world-cup-fan-outfit-prompts': 'worldCupFanOutfitPrompts',
      '50-world-cup-2026-ai-prompts': 'fiftyWorldCup2026AiPrompts',
      '50-wimbledon-2026-ai-prompts': 'fiftyWimbledon2026AiPrompts',
      'ai-product-photo-to-ecommerce-listing': 'aiProductPhotoToEcommerceListing',
      '50-ai-sticker-design-prompts': 'fiftyAiStickerDesignPrompts',
      '50-ai-packaging-design-prompts': 'fiftyAiPackagingDesignPrompts',
      '50-ai-makeover-prompts': 'fiftyAiMakeoverPrompts',
      'ai-travel-scrapbook-templates': 'aiTravelScrapbookTemplates',
      'ai-travel-itinerary-templates': 'aiTravelItineraryTemplates',
      'phonics-flashcards-ai-templates': 'phonicsFlashcardsAiTemplates',
      'subject-flashcards-biology-chemistry-ai': 'subjectFlashcardsBiologyChemistryAi',
      'vocabulary-flashcards-ai-templates': 'vocabularyFlashcardsAiTemplates',
      'competitor-comparison-infographics-ai': 'competitorComparisonInfographicsAi',
      'multimodal-ai-educational-publishing': 'multimodalAiEducationalPublishing',
      'programmatic-seo-dtc-visual-first': 'programmaticSeoDtcVisualFirst',
            'brazil-argentina-soccer-poster-prompts': 'brazilArgentinaSoccerPosterPrompts',
            'portugal-soccer-poster-prompts': 'portugalSoccerPosterPrompts',
            'ai-1v1-soccer-rivalry-prompts': 'ai1v1SoccerRivalryPrompts',
            'france-soccer-poster-prompts': 'franceSoccerPosterPrompts',
            'style-transfer-ai-guide': 'styleTransferAiGuide',
            'ai-product-photo-generator-guide': 'aiProductPhotoGeneratorGuide',
            'curify-webflow-programmatic-seo-integration': 'curifyWebflowProgrammaticSeoIntegration',
            'cross-border-ecommerce-multilingual-seo-case': 'crossBorderEcommerceMultilingualSeoCase',
            'world-cup-2026-ai-prompt-hub': 'worldCup2026AiPromptHub',
            'fifa-2026-host-city-travel-guide': 'fifa2026HostCityTravelGuide',
            'world-cup-2026-top-contenders': 'worldCup2026TopContenders',
            'argentina-france-2022-world-cup-final': 'argentinaFrance2022WorldCupFinal',
      'one-person-companies-vs-100-person-teams': 'onePersonCompaniesVs100PersonTeams',
      'self-improving-multimodal-search': 'selfImprovingMultimodalSearch',
      'ai-event-card-manus-vs-genspark-vs-curify': 'aiEventCardManusGensparkCurify',
      'ai-last-mile-problem': 'aiLastMileProblem',
      'visual-search-platform-comparison': 'visualSearchPlatformComparison',
      'agentic-generative-capability': 'agenticGenerativeCapability'
    };
    
    namespace = namespaceMap[slug] || namespace;
    
    // Determine category from blog data (use the category field if available, otherwise fallback to tag-based mapping)
    let category = blog.category;
    let relatedCategories = [category]; // simplified - just use the same category
    
    // If no category field, determine from tag (fallback for backward compatibility)
    if (!category) {
      const tag = blog.tag?.toLowerCase() || '';
      if (tag.includes('ai platform') || tag.includes('ai architecture') || tag.includes('ai industry') || tag.includes('data science')) {
        category = 'ds-ai-engineering';
      } else if (tag.includes('video translation') || tag.includes('localization')) {
        category = 'video-translation';
      } else if (tag.includes('video analysis') || tag.includes('video enhancement') || tag.includes('animation') || tag.includes('generative tools') || tag.includes('tools pipeline') || tag.includes('ai audio') || tag.includes('accessibility')) {
        category = 'creator-tools';
      } else if (tag.includes('traditional medicine') || tag.includes('data visualization')) {
        category = 'nano-banana-prompts';
      } else if (tag.includes('cultural heritage')) {
        category = 'culture';
      } else if (tag.includes('ai tools')) {
        category = 'nano-banana-prompts';
      } else {
        category = 'creator-tools'; // default
      }
      relatedCategories = [category];
    }
    
    blogPosts[slug] = {
      titleKey: "title",
      descriptionKey: slug === 'mbti-character-generator' ? "intro.description1" : slug === 'content-tagging-system' ? "intro.title" : "intro",
      image: blog.image,
      category: category,
      relatedCategories: relatedCategories,
      namespace: namespace
    };
  });
  
  return blogPosts;
}

// Blog post configuration - dynamically generated from blogs data
export const blogPosts = createBlogPostsConfig();

// Define which keys exist for each blog post type
export const availableKeys: Record<string, string[]> = {
  'urlToProductVideo': ['intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'videoToLearningPack': ['intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'footballerMbtiTypes': ['intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiPlatform': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'qaBotToTask': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'ageAi': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'storyboardLabeling': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'videoEnhancement': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'videoEvaluation': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'storyboardToPipeline': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'agentsVsWorkflows': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'aeVsComfyui': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'translateYoutubevideo': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'translateYoutubeVideoToEnglish': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'aiYoutubeVideoTranslator': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'whatIsVoiceCloning': ['intro', 'whatIsTitle', 'whatIsContent', 'howWorksTitle', 'howWorksContent', 'toolsTitle', 'toolsContent', 'useCasesTitle', 'useCasesContent', 'ethicalTitle', 'ethicalContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'voiceCloningTools': ['title', 'metaDescription', 'date', 'readTime', 'intro', 'whoThisIsForTitle', 'whoThisIsForContent', 'buyersGuideTitle', 'buyersGuideContent', 'methodologyTitle', 'methodologyContent', 'toolsTitle', 'toolsIntro', 'tool1Name', 'tool1Tagline', 'tool1BestFor', 'tool1Pricing', 'tool1Languages', 'tool1Limitation', 'tool1WhenToPick', 'tool2Name', 'tool2Tagline', 'tool2BestFor', 'tool2Pricing', 'tool2Languages', 'tool2Limitation', 'tool2WhenToPick', 'tool3Name', 'tool3Tagline', 'tool3BestFor', 'tool3Pricing', 'tool3Languages', 'tool3Limitation', 'tool3WhenToPick', 'comparisonTitle', 'comparisonIntro', 'decisionRubricTitle', 'decisionRubricContent', 'curifyCalloutTitle', 'curifyCalloutContent', 'complianceTitle', 'complianceContent', 'faqTitle', 'faq1Q', 'faq1A', 'faq2Q', 'faq2A', 'faq3Q', 'faq3A', 'faq4Q', 'faq4A', 'faq5Q', 'faq5A', 'faq6Q', 'faq6A', 'conclusionTitle', 'conclusionContent', 'ctaText', 'ctaLink'],
  'f5TtsVoiceCloning': ['intro', 'whatIsTitle', 'whatIsContent', 'howWorksTitle', 'howWorksContent', 'toolsTitle', 'toolsContent', 'useCasesTitle', 'useCasesContent', 'ethicalTitle', 'ethicalContent', 'PipelineTitle', 'PipelineContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'aslVideoTranslator': ['intro', 'whatIsTitle', 'whatIsContent', 'whenNeededTitle', 'whenNeededContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'videoTranscriptionBusinessGuide': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'toolsTitle', 'toolsContent', 'useCasesTitle', 'useCasesContent', 'upsellTitle', 'upsellContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'videoTranscriptionTechnicalDeepDive': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'challengesTitle', 'challengesContent', 'productionTitle', 'productionContent', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'chineseHerbalMedicineVisualGuide': ['intro', 'whatIsTitle', 'whatIsContent', 'historyTitle', 'historyContent', 'benefitsTitle', 'benefitsContent', 'popularTitle', 'popularContent', 'usageTitle', 'usageContent', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'evolutionTimelinesVisualization': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'chineseCostumeHistoryInfographic': ['intro', 'whatIsTitle', 'whatIsContent', 'dynastiesTitle', 'dynastiesContent', 'characteristicsTitle', 'characteristicsContent', 'modernTitle', 'modernContent', 'culturalTitle', 'culturalContent', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'creativeAiToolsWebsites': ['intro', 'whatIsTitle', 'whatIsContent', 'inspirationTitle', 'inspirationContent', 'featuredTitle', 'featuredContent', 'aiTitle', 'aiContent', 'aiFeaturedTitle', 'aiFeaturedContent', 'conclusionTitle', 'conclusionContent'],
  'nanoBananaPromptEcosystem': ['title', 'slug', 'metaDescription', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'ecosystemTitle', 'ecosystemContent', 'seoTitle', 'seoContent', 'generatorTitle', 'generatorContent', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'promptExamplesTitle', 'promptExamplesContent', 'promptTemplatesTitle', 'promptTemplatesContent'],
  'tenPromptingTipsNanoBanana': ['title', 'slug', 'metaDescription', 'date', 'readTime', 'intro', 'whyNanoBananaTitle', 'whyNanoBananaContent', 'tip1Title', 'tip1Content', 'tip2Title', 'tip2Content', 'tip3Title', 'tip3Content', 'tip4Title', 'tip4Content', 'tip5Title', 'tip5Content', 'tip6Title', 'tip6Content', 'tip7Title', 'tip7Content', 'tip8Title', 'tip8Content', 'tip9Title', 'tip9Content', 'tip10Title', 'tip10Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent', 'templatesTitle', 'faq1Question', 'faq1Answer', 'faq2Question', 'faq2Answer', 'faq3Question', 'faq3Answer', 'faq4Question', 'faq4Answer', 'faq5Question', 'faq5Answer', 'tip1ExampleTitle', 'tip1Example', 'tip1PromptTitle', 'tip2Example', 'tip3Example', 'tip4Example', 'tip5Example', 'tip6Example', 'tip7Example', 'tip8Example', 'tip9Example', 'tip10Example'],
  'curifyNanoBananaTemplateTips': ['title', 'slug', 'metaDescription', 'date', 'readTime', 'intro', 'whyNanoBananaTitle', 'whyNanoBananaContent', 'tip1Title', 'tip1Content', 'tip2Title', 'tip2Content', 'tip3Title', 'tip3Content', 'tip4Title', 'tip4Content', 'tip5Title', 'tip5Content', 'tip6Title', 'tip6Content', 'tip7Title', 'tip7Content', 'tip8Title', 'tip8Content', 'tip9Title', 'tip9Content', 'tip10Title', 'tip10Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent', 'templatesTitle', 'faq1Question', 'faq1Answer', 'faq2Question', 'faq2Answer', 'faq3Question', 'faq3Answer', 'faq4Question', 'faq4Answer', 'faq5Question', 'faq5Answer', 'tip1ExampleTitle', 'tip1Example', 'tip1PromptTitle'],
  'tenPromptingTipsVideoGeneration': ['title', 'slug', 'metaDescription', 'date', 'readTime', 'intro', 'tip1Title', 'tip1Content', 'tip2Title', 'tip2Content', 'tip3Title', 'tip3Content', 'tip4Title', 'tip4Content', 'tip5Title', 'tip5Content', 'tip6Title', 'tip6Content', 'tip7Title', 'tip7Content', 'tip8Title', 'tip8Content', 'tip9Title', 'tip9Content', 'tip10Title', 'tip10Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent', 'successMetricsTitle', 'qualityMetricsTitle', 'engagementMetricsTitle', 'efficiencyMetricsTitle', 'nextLearningTitle', 'advancedGuideTitle', 'cinematicTechniquesTitle', 'aiModelComparisonTitle', 'commercialApplicationsTitle', 'tip1ExampleTitle', 'tip2ExampleTitle', 'tip3ExampleTitle', 'tip4ExampleTitle', 'tip5ExampleTitle', 'tip6ExampleTitle', 'tip7ExampleTitle', 'tip8ExampleTitle', 'tip9ExampleTitle', 'tip10ExampleTitle', 'successMetricsContent', 'engagementMetricsContent', 'efficiencyMetricsContent', 'learningResourcesContent', 'quickStartSummaryTitle', 'quickStartSubtitle', 'beginnerPathTitle', 'advancedPathTitle', 'quickStartBeginnerSteps', 'quickStartAdvancedSteps', 'beforeAfterTitle', 'basicPromptTitle', 'basicPromptBoxTitle', 'basicPromptText', 'basicPromptIssues', 'professionalPromptTitle', 'professionalPromptBoxTitle', 'professionalPromptText', 'professionalPromptImprovements', 'platformOptimizationTitle', 'tiktokTitle', 'youtubeTitle', 'instagramTitle', 'tiktokFeatures', 'youtubeFeatures', 'instagramFeatures', 'platformOptimizationTemplateTitle', 'platformOptimizationTemplateContent', 'platformOptimizationTemplateDisplay', 'troubleshootingTitle', 'problem1Title', 'problem1Cause', 'problem1Solution', 'problem2Title', 'problem2Cause', 'problem2Solution', 'problem3Title', 'problem3Cause', 'problem3Solution', 'problem4Title', 'problem4Cause', 'problem4Solution', 'qualityControlTitle', 'qcSubtitle', 'characterIdentityTitle', 'visualQualityTitle', 'storyFlowTitle', 'technicalSpecsTitle', 'characterIdentityChecklist', 'visualQualityChecklist', 'storyFlowChecklist', 'technicalSpecsChecklist', 'scoringText', 'platformComparisonTitle', 'platformComparisonTable', 'actionPlanTitle', 'week1Title', 'week2Title', 'week3Title', 'week4Title', 'week1Tasks', 'week2Tasks', 'week3Tasks', 'week4Tasks', 'tip1Example', 'tip2Example', 'tip3Example', 'tip4Example', 'tip5Example', 'tip6Example', 'tip7Example', 'tip8Example', 'tip9Example', 'tip10Example', 'videoGenerationToolsUrl'],
  'imageGenerationModelComparison': ['intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'dalle3Title', 'dalle3Content', 'midjourneyTitle', 'midjourneyContent', 'stableDiffusionTitle', 'stableDiffusionContent', 'comparisonTitle', 'comparisonContent', 'qualityTitle', 'qualityContent', 'speedTitle', 'speedContent', 'costTitle', 'costContent', 'useCasesTitle', 'useCasesContent', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent', 'faqTitle', 'faq1Question', 'faq1Answer', 'faq2Question', 'faq2Answer', 'faq3Question', 'faq3Answer', 'faq4Question', 'faq4Answer', 'futureTrendsTitle', 'marketingMaterialsTitle', 'marketingMaterialsContent', 'creativeProjectsTitle', 'creativeProjectsContent', 'technicalApplicationsTitle', 'technicalApplicationsContent', 'integrationDifficultyTitle', 'unifiedWorkflowTitle', 'unifiedWorkflowContent', 'promptOptimizationTitle', 'promptOptimizationContent', 'assetManagementTitle', 'assetManagementContent', 'batchProcessingTitle', 'batchProcessingContent', 'technicalAdvancementsTitle', 'marketEvolutionTitle'],
  'lipSyncBusinessGuide': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'toolsTitle', 'toolsContent', 'useCasesTitle', 'useCasesContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'lipSyncTechnicalDeepDive': ['intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'character-prompt-generator': ['title', 'metaDescription', 'publishedDate', 'readTime', 'category', 'heroImageAlt', 'intro', 'whatWeShip', 'howToUse', 'workedExamples', 'mbtiIndex', 'footer'],
  'visualLearningTools': ['title', 'publishedDate', 'readTime', 'category', 'introduction', 'whatWeOffer', 'forStudents', 'forParents', 'forTeachers', 'howToGetStarted', 'successStories', 'footer'],
  'bestAiTools': ['title', 'metaDescription', 'publishedDate', 'readTime', 'category', 'heroImageAlt', 'intro', 'whoThisIsForTitle', 'whoThisIsForContent', 'buyersGuideTitle', 'buyersGuideContent', 'methodologyTitle', 'methodologyContent', 'toolsTitle', 'toolsIntro', 'tool1Name', 'tool1Tagline', 'tool1BestFor', 'tool1Pricing', 'tool1Languages', 'tool1Limitation', 'tool1WhenToPick', 'tool2Name', 'tool2Tagline', 'tool2BestFor', 'tool2Pricing', 'tool2Languages', 'tool2Limitation', 'tool2WhenToPick', 'tool3Name', 'tool3Tagline', 'tool3BestFor', 'tool3Pricing', 'tool3Languages', 'tool3Limitation', 'tool3WhenToPick', 'comparisonTitle', 'comparisonIntro', 'decisionRubricTitle', 'decisionRubricContent', 'curifyCalloutTitle', 'curifyCalloutContent', 'faqTitle', 'faq1Q', 'faq1A', 'faq2Q', 'faq2A', 'faq3Q', 'faq3A', 'faq4Q', 'faq4A', 'faq5Q', 'faq5A', 'faq6Q', 'faq6A', 'conclusionTitle', 'conclusionContent', 'footer'],
  'bestProgrammaticSeoTools': ['title', 'metaDescription', 'publishedDate', 'readTime', 'category', 'heroImageAlt', 'heroImage', 'heroCtaText', 'heroCtaHref', 'intro', 'whoThisIsForTitle', 'whoThisIsForContent', 'buyersGuideTitle', 'buyersGuideContent', 'methodologyTitle', 'methodologyContent', 'toolsTitle', 'toolsIntro', 'tool1Name', 'tool1Tagline', 'tool1BestFor', 'tool1Pricing', 'tool1Languages', 'tool1Limitation', 'tool1WhenToPick', 'tool2Name', 'tool2Tagline', 'tool2BestFor', 'tool2Pricing', 'tool2Languages', 'tool2Limitation', 'tool2WhenToPick', 'tool3Name', 'tool3Tagline', 'tool3BestFor', 'tool3Pricing', 'tool3Languages', 'tool3Limitation', 'tool3WhenToPick', 'comparisonTitle', 'comparisonIntro', 'decisionRubricTitle', 'decisionRubricContent', 'curifyCalloutTitle', 'curifyCalloutContent', 'faqTitle', 'faq1Q', 'faq1A', 'faq2Q', 'faq2A', 'faq3Q', 'faq3A', 'faq4Q', 'faq4A', 'faq5Q', 'faq5A', 'faq6Q', 'faq6A', 'conclusionTitle', 'conclusionContent', 'footer'],
  'aiContentProductionSystem': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'step6Title', 'step6Content', 'step7Title', 'step7Content', 'step8Title', 'step8Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'imageToNarrativeVideo': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'technicalTitle', 'technicalIntro', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'businessTitle', 'educationTitle', 'educationContent', 'educationExample1', 'educationExample2', 'educationExample3', 'marketingTitle', 'marketingContent', 'marketingExample1', 'marketingExample2', 'marketingExample3', 'trainingTitle', 'trainingContent', 'trainingExample1', 'trainingExample2', 'trainingExample3', 'entertainmentTitle', 'entertainmentContent', 'entertainmentExample1', 'entertainmentExample2', 'entertainmentExample3', 'examplesTitle', 'techStackTitle', 'toolsTitle', 'toolsContent', 'gettingStartedTitle', 'quickStartTitle', 'iranExampleTitle', 'iranExampleDescription', 'iranFeature1', 'iranFeature2', 'iranFeature3', 'iranFeature4', 'vocabularyExampleTitle', 'vocabularyExampleDescription', 'vocabularyImages', 'vocabularyFeature1', 'vocabularyFeature2', 'vocabularyFeature3', 'vocabularyFeature4', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'ctaTitle', 'ctaSubtitle', 'ctaButton', 'curifyToolTitle', 'curifyToolDesc', 'curifyFeatures', 'curifyUseCases', 'curifyPricing', 'runwayToolTitle', 'runwayToolDesc', 'runwayFeatures', 'runwayUseCases', 'runwayPricing', 'pikaToolTitle', 'pikaToolDesc', 'pikaFeatures', 'pikaUseCases', 'pikaPricing', 'stableToolTitle', 'stableToolDesc', 'stableFeatures', 'stableUseCases', 'stablePricing', 'insightsTitle', 'insight1Title', 'insight1Content', 'insight2Title', 'insight2Content', 'insight3Title', 'insight3Content', 'promptExamplesTitle', 'educationalPromptTitle', 'educationalPromptDesc', 'marketingPromptTitle', 'marketingPromptDesc', 'storytellingPromptTitle', 'storytellingPromptDesc', 'futureTitle', 'trendsTitle', 'trend1', 'trend2', 'trend3', 'trend4', 'opportunitiesTitle', 'opportunity1', 'opportunity2', 'opportunity3', 'opportunity4', 'bestPracticesTitle', 'practice1Title', 'practice1Content', 'practice2Title', 'practice2Content', 'practice3Title', 'practice3Content'],
  'whatIsInfographics': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'introContent', 'definitionTitle', 'definitionContent', 'visualElement', 'visualElementDesc', 'contentElement', 'contentElementDesc', 'designElement', 'designElementDesc', 'useCasesTitle', 'digitalTab', 'physicalTab', 'examplesLabel', 'nanoBananaTitle', 'nanoBananaIntro', 'templateType', 'insightsTitle', 'insight1Title', 'insight1Content', 'insight2Title', 'insight2Content', 'insight3Title', 'insight3Content', 'promptExamplesTitle', 'technicalPromptTitle', 'technicalPromptDesc', 'culturalPromptTitle', 'culturalPromptDesc', 'businessPromptTitle', 'businessPromptDesc', 'futureTitle', 'trendsTitle', 'trend1', 'trend2', 'trend3', 'trend4', 'opportunitiesTitle', 'opportunity1', 'opportunity2', 'opportunity3', 'opportunity4', 'conclusionTitle', 'conclusionContent', 'digitalCase1Title', 'digitalCase1Desc', 'digitalCase1Example', 'digitalCase2Title', 'digitalCase2Desc', 'digitalCase2Example', 'digitalCase3Title', 'digitalCase3Desc', 'digitalCase3Example', 'digitalCase4Title', 'digitalCase4Desc', 'digitalCase4Example', 'physicalCase1Title', 'physicalCase1Desc', 'physicalCase1Example', 'physicalCase2Title', 'physicalCase2Desc', 'physicalCase2Example', 'physicalCase3Title', 'physicalCase3Desc', 'physicalCase3Example', 'physicalCase4Title', 'physicalCase4Desc', 'physicalCase4Example', 'nanoExample1Title', 'nanoExample1Desc', 'nanoExample1Template', 'nanoExample2Title', 'nanoExample2Desc', 'nanoExample2Template', 'nanoExample3Title', 'nanoExample3Desc', 'nanoExample3Template'],
  'seriesInfographicVsNotebookLM': ['title', 'date', 'readTime', 'introTitle', 'introContent', 'whatIsInfographicTitle', 'whatIsInfographicContent', 'exampleTitle', 'exampleContent', 'whatIsNotebookLMTitle', 'whatIsNotebookLMContent', 'notebookLMExampleTitle', 'notebookLMExampleContent', 'comparisonTitle', 'categoryHeader', 'infographicHeader', 'notebookLMHeader', 'category1', 'infographic1', 'notebooklm1', 'category2', 'infographic2', 'notebooklm2', 'category3', 'infographic3', 'notebooklm3', 'category4', 'infographic4', 'notebooklm4', 'category5', 'infographic5', 'notebooklm5', 'category6', 'infographic6', 'notebooklm6', 'whenUseInfographicTitle', 'useCase1Title', 'useCase1Content', 'useCase2Title', 'useCase2Content', 'useCase3Title', 'useCase3Content', 'useCase4Title', 'useCase4Content', 'whenUseNotebookLMTitle', 'notebookUseCase1Title', 'notebookUseCase1Content', 'notebookUseCase2Title', 'notebookUseCase2Content', 'notebookUseCase3Title', 'notebookUseCase3Content', 'notebookUseCase4Title', 'notebookUseCase4Content', 'combineTitle', 'combineContent', 'step1', 'step2', 'step3', 'step4', 'promptExampleTitle', 'promptTitle', 'promptDesc', 'conclusionTitle', 'conclusionContent', 'conclusionContent2', 'ctaText', 'ctaLink', 'seoKeywords'],
  'mbtiCharacterGenerator': ['title', 'publishedDate', 'readTime', 'category', 'intro.title', 'intro.description1', 'intro.description2', 'intro.example.title', 'whatIs.title', 'whatIs.description1', 'whatIs.description2', 'whatIs.thinkOfItAs', 'whatIs.thinkOfItAsDescription', 'examples.title', 'examples.description', 'examples.nba.title', 'examples.nba.description', 'examples.nba.intj', 'examples.nba.esfp', 'examples.animals.title', 'examples.animals.description', 'examples.animals.infp', 'examples.animals.estp', 'examples.movies.title', 'examples.movies.description', 'examples.movies.enfp', 'examples.movies.istj', 'howItWorks.title', 'howItWorks.description', 'howItWorks.behindTheScenes', 'howItWorks.systemDescription', 'howItWorks.conclusion', 'whyNotRegular.title', 'whyNotRegular.description', 'whyNotRegular.traditional.title', 'whyNotRegular.nanoBanana.title', 'whyNotRegular.conclusion', 'useCases.title', 'useCases.description', 'useCases.socialMedia.title', 'useCases.creative.title', 'useCases.marketing.title', 'tryNow.title', 'tryNow.description', 'tryNow.explore.title', 'tryNow.browse.title', 'customize.title', 'customize.description', 'customize.bonus.title', 'customize.bonus.description', 'customize.bonus.conclusion', 'finalThoughts.title', 'finalThoughts.description', 'finalThoughts.formula', 'finalThoughts.conclusion', 'relatedReads.title', 'relatedReads.items', 'faq.title', 'faq.questions', 'footer.tags', 'footer.questions'],
  'contentTaggingSystem': ['title', 'publishedDate', 'readTime', 'category', 'intro', 'whyTagsMatter', 'coreChallenges', 'threeLayerApproach', 'keyInsight', 'pinterestPlatform', 'ruleOfThumb', 'finalThought', 'footer'],
  'bilingual-ai-flashcards-early-childhood-education': ['title', 'date', 'readTime', 'tag', 'image', 'category', 'intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'templatesTitle', 'templatesIntro', 'template1Title', 'template1Prompt', 'template2Title', 'template2Prompt', 'template3Title', 'template3Prompt', 'benefitsTitle', 'benefitsContent', 'toolsTitle', 'toolsContent', 'bestPracticesTitle', 'bestPracticesContent', 'conclusionTitle', 'conclusionContent'],
  'ugcVideoTranslationScalingTiktoksShortsGlobalMarkets': ['title', 'date', 'readTime', 'tag', 'image', 'category', 'intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'technicalTitle', 'timingTitle', 'timingContent', 'emotionTitle', 'emotionContent', 'platformTitle', 'platformContent', 'toolsTitle', 'toolsContent', 'monetizationTitle', 'monetizationContent', 'caseStudiesTitle', 'caseStudy1Title', 'caseStudy1Content', 'caseStudy2Title', 'caseStudy2Content', 'bestPracticesTitle', 'bestPracticesContent', 'conclusionTitle', 'conclusionContent'],
  'aifacelesschannelpipeline': ['title', 'date', 'readTime', 'category', 'tag', 'image', 'metaDescription', 'seoKeywords', 'intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'curifyTitle', 'curifyContent', 'monetizationTitle', 'monetizationContent', 'examplesTitle', 'examplesContent', 'metricsTitle', 'metricsContent', 'scalingTitle', 'scalingContent', 'ctaText', 'ctaLink', 'conclusionTitle', 'conclusionContent'],
  'aiCollageDigitalWallpaperGuide': ['title', 'slug', 'metaDescription', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'nanoBananaTitle', 'nanoBananaContent', 'basicTemplateTitle', 'basicTemplateDescription', 'basicTemplatePrompt', 'seasonalTitle', 'seasonalContent', 'winterForestTitle', 'winterForestDescription', 'winterForestPrompt', 'autumnVibesTitle', 'autumnVibesDescription', 'autumnVibesPrompt', 'wallpaperTitle', 'wallpaperContent', 'advancedTitle', 'advancedContent', 'toolsTitle', 'toolsContent', 'conclusionTitle', 'conclusionContent', 'ctaTitle', 'ctaDescription', 'ctaButton'],
  'weirdScienceFactsClassroomEngagement': ['title', 'slug', 'metaDescription', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'bilingualTitle', 'bilingualContent', 'templateTitle', 'templateDescription', 'templatePrompt', 'topFactsTitle', 'topFactsContent', 'jupiterDiamondsTitle', 'jupiterDiamondsDescription', 'jupiterDiamondsPrompt', 'octopusThreeHeartsTitle', 'octopusThreeHeartsDescription', 'octopusThreeHeartsPrompt', 'honeyNeverSpoilsTitle', 'honeyNeverSpoilsDescription', 'honeyNeverSpoilsPrompt', 'lightningHotterSunTitle', 'lightningHotterSunDescription', 'lightningHotterSunPrompt', 'classroomTitle', 'classroomContent', 'assessmentTitle', 'assessmentContent', 'toolsTitle', 'toolsContent', 'conclusionTitle', 'conclusionContent', 'ctaTitle', 'ctaDescription', 'ctaButton'],
  'mbiRelationshipStyleVisualizer': ['title', 'slug', 'metaDescription', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'coupleTitle', 'coupleContent', 'relationshipTemplateTitle', 'relationshipTemplateDescription', 'relationshipTemplatePrompt', 'outfitTitle', 'outfitContent', 'intjTechwearTitle', 'intjTechwearDescription', 'intjTechwearPrompt', 'esfpFestivalTitle', 'esfpFestivalDescription', 'esfpFestivalPrompt', 'infjAcademicTitle', 'infjAcademicDescription', 'infjAcademicPrompt', 'estpAthleticTitle', 'estpAthleticDescription', 'estpAthleticPrompt', 'combinationsTitle', 'combinationsContent', 'fashionTitle', 'fashionContent', 'toolsTitle', 'toolsContent', 'conclusionTitle', 'conclusionContent', 'ctaTitle', 'ctaDescription', 'ctaButton'],
  'aiReshapingDataWorkflow': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'mlEngineerVsAiEngineer': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiEngineeringHardTruth': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiContentFactoryForAgencies': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'industrialAiForIllustratorIp': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'surtexLicensingPlaybookSurfaceDesigners': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'ipMerchDesignAiWorkflow': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiStickerDesignGuide': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiDieCutStickerDesign': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiPackagingDesignGuide': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiMakeoverTemplates': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'worldCupFanOutfitPrompts': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'fiftyWorldCup2026AiPrompts': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'fiftyWimbledon2026AiPrompts': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiProductPhotoToEcommerceListing': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'fiftyAiStickerDesignPrompts': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'fiftyAiPackagingDesignPrompts': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'fiftyAiMakeoverPrompts': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiTravelScrapbookTemplates': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiTravelItineraryTemplates': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'phonicsFlashcardsAiTemplates': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'subjectFlashcardsBiologyChemistryAi': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'vocabularyFlashcardsAiTemplates': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'competitorComparisonInfographicsAi': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'multimodalAiEducationalPublishing': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'programmaticSeoDtcVisualFirst': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'brazilArgentinaSoccerPosterPrompts': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'portugalSoccerPosterPrompts': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'jerseyTitle', 'jerseyContent', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'ai1v1SoccerRivalryPrompts': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'franceSoccerPosterPrompts': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'styleTransferAiGuide': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiProductPhotoGeneratorGuide': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'curifyWebflowProgrammaticSeoIntegration': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'step6Title', 'step6Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'crossBorderEcommerceMultilingualSeoCase': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'step6Title', 'step6Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'worldCup2026AiPromptHub': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'modelsTitle', 'modelsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'fifa2026HostCityTravelGuide': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'worldCup2026TopContenders': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'argentinaFrance2022WorldCupFinal': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'onePersonCompaniesVs100PersonTeams': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'selfImprovingMultimodalSearch': ['title', 'date', 'readTime', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiEventCardManusGensparkCurify': ['title', 'date', 'readTime', 'heroImage', 'heroImageAlt', 'heroCtaText', 'heroCtaHref', 'intro', 'whatIsTitle', 'whatIsContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'aiLastMileProblem': ['title', 'date', 'readTime', 'heroImage', 'heroImageAlt', 'heroCtaText', 'heroCtaHref', 'intro', 'whatIsTitle', 'whatIsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'metaDescription', 'seoKeywords'],
  'visualSearchPlatformComparison': ['title', 'metaDescription', 'seoKeywords', 'date', 'readTime', 'heroImage', 'heroImageAlt', 'intro', 'whatIsTitle', 'whatIsContent', 'whyTitle', 'whyContent', 'howTitle', 'step1Title', 'step1Content', 'step2Title', 'step2Content', 'step3Title', 'step3Content', 'step4Title', 'step4Content', 'step5Title', 'step5Content', 'useCasesTitle', 'useCasesContent', 'toolsTitle', 'toolsContent', 'challengesTitle', 'challengesContent', 'curifyTitle', 'curifyContent', 'conclusionTitle', 'conclusionContent', 'ctaText', 'ctaLink'],
  'agenticGenerativeCapability': ['title', 'displayTitle', 'metaDescription', 'seoKeywords', 'date', 'readTime', 'heroImage', 'heroImageAlt', 'heroCaption', 'heroCtaText', 'heroCtaHref', 'intro', 'differencesTitle', 'differencesIntro', 'ontologyImage', 'ontologyImageAlt', 'ontologyCaption', 'differencesBridge', 'guidanceTitle', 'guidanceGptLabel', 'guidanceGptContent', 'guidanceCanvaLabel', 'guidanceCanvaContent', 'guidanceCurifyLabel', 'guidanceCurifyContent', 'stressTestTitle', 'stressTestIntro', 'economicsTitle', 'economicsImage', 'economicsImageAlt', 'economicsCaption', 'economicsGptLabel', 'economicsGptContent', 'economicsCanvaLabel', 'economicsCanvaContent', 'economicsCurifyLabel', 'economicsCurifyIntro', 'economicsBullet1Label', 'economicsBullet1Content', 'economicsBullet2Label', 'economicsBullet2Content', 'economicsBullet3Label', 'economicsBullet3Content', 'economicsCurifyConclusion', 'chiikawaTitle', 'chiikawaImage', 'chiikawaImageAlt', 'chiikawaCaption', 'chiikawaGptCanvaLabel', 'chiikawaGptCanvaContent', 'chiikawaCurifyLabel', 'chiikawaCurifyContent', 'readingTitle', 'readingImage', 'readingImageAlt', 'readingCaption', 'readingGptLabel', 'readingGptContent', 'readingCanvaLabel', 'readingCanvaContent', 'readingCurifyLabel', 'readingCurifyContent', 'valueTitle', 'valueIntro', 'businessCaseTitle', 'businessCaseLead', 'businessCaseContent', 'direction1Label', 'direction1Content', 'direction2Label', 'direction2Content', 'direction3Label', 'direction3Content', 'businessCaseImage', 'businessCaseImageAlt', 'businessCaseCaption', 'businessValuesLead', 'businessValue1Label', 'businessValue1Content', 'businessValue2Label', 'businessValue2Content', 'businessValue3Label', 'businessValue3Content', 'conclusionTitle', 'conclusionParagraph1', 'conclusionParagraph2', 'conclusionParagraph3']
};
