// app/[locale]/agreement/page.tsx
import Head from 'next/head';

export default function UserAgreementPage() {
  return (
    <>
      <Head>
        <title>User Agreement | Curify Studio</title>
      </Head>
      <div className="max-w-5xl mx-auto p-20 text-gray-800 text-base sm:text-lg leading-relaxed">
        <h1 className="text-2xl sm:text-3xl font-bold mb-6">🧑‍⚖️ User Agreement (Terms of Use)</h1>
        <p className="mb-6">Effective Date: September 13, 2025</p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">1. License for Processing</h2>
        <p className="mb-6">
          By uploading content, you grant Curify Studio a limited license to process the content solely for the purpose of delivering services (e.g., translation, dubbing, subtitle removal, generation). We do not use your content for model training or resale.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">2. Derivative Work Responsibility</h2>
        <p className="mb-6">
          Translations, dubbed audio, and generated media may qualify as derivative works under copyright law. You are solely responsible for ensuring that you have the legal right to transform or translate the original content. Curify does not assume liability for unauthorized use of copyrighted materials.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">3. Generative Output Ownership</h2>
        <p className="mb-6">
          You retain rights to outputs generated by our system, provided you have rights to the inputs. You may use the results commercially or non-commercially at your discretion. We disclaim liability for third-party claims arising from your use of the generated content.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">4. No Copyright Circumvention</h2>
        <p className="mb-6">
          The subtitle removal tool is intended for lawful editing only. You must not use it to bypass watermarks, rights notices, or protected captions. Any misuse for piracy or content stripping is strictly prohibited.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">5. Content Moderation</h2>
        <p className="mb-6">
          We reserve the right to suspend or terminate accounts for misuse, including impersonation, harassment, misinformation, hate speech, or uploading infringing material.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">6. Generated Content Disclaimer</h2>
        <p className="mb-6">
          AI-generated outputs (translations, dubbed voices, visuals) may be inaccurate or inappropriate. Do not rely on these outputs for legal, medical, or safety-critical use cases without human review.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">7. Feedback and Model Improvement</h2>
        <p className="mb-6">
          We may use anonymized data to improve quality and system performance unless you opt out. GDPR-region users must explicitly opt in.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">8. Service Availability</h2>
        <p className="mb-6">
          Curify Studio may occasionally be offline for maintenance or due to unforeseen issues. We do not guarantee uninterrupted access or the availability of beta features.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">9. Export Control</h2>
        <p className="mb-6">
          Our services and models are subject to U.S. export control laws. You agree not to export or re-export our technology to embargoed nations or restricted parties.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">10. Indemnification</h2>
        <p className="mb-6">
          You agree to indemnify and hold harmless Curify Studio, its team, and partners from any legal claims or damages arising from your use of the service or your violation of these terms or any applicable law.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold mt-8 mb-3">11. Governing Law</h2>
        <p className="mb-6">
          These terms are governed by the laws of the State of California, USA. Any disputes shall be resolved in the courts located in San Francisco County, California.
        </p>
      </div>
    </>
  );
}
