import { PageLocale } from "@/lib/locale_utils";
import {
  nanoRegistry,
  fillPrompt,
  getTemplateTopics,
  getTemplateView,
  getTemplateViewWithTranslations,
  toSlug,
  type ImageView,
  type NanoRegistry,
  type RawNanoImageRecord,
  type TemplateView,
  type TranslateFn,
} from "@/lib/nano_utils";

export type CircularNeighbors<T> = {
  prev: T;
  current: T;
  next: T;
  index: number;
  total: number;
};

export type ExampleI18n = {
  title: string;
  description: string;
  metaDescription: string;
};

/**
 * Read locale-specific SEO copy for an example from
 * messages/<locale>/example.json. Returns null if the locale file
 * doesn't exist or the example has no entry — caller should fall back
 * to template-level i18n in that case.
 *
 * Only allow_i18n examples should have entries in these files; the
 * EN seeds are generated by scripts/generate_example_i18n_seeds.cjs
 * and the other 9 locales are filled by i18n_autotranslate.cjs.
 */
export async function getExampleI18n(
  exampleId: string,
  locale: PageLocale
): Promise<ExampleI18n | null> {
  try {
    const mod = await import(`@/messages/${locale}/example.json`);
    const data = (mod.default ?? mod) as Record<
      string,
      Partial<ExampleI18n> | undefined
    >;
    const entry = data[exampleId];
    if (!entry || !entry.title) return null;
    return {
      title: entry.title || "",
      description: entry.description || "",
      metaDescription: entry.metaDescription || "",
    };
  } catch {
    return null;
  }
}

export type NanoExampleDetail = RawNanoImageRecord & {
  base_prompt: string;
  filled_prompt: string;
};

export type NanoExampleDetailData = {
  image: ImageView;
  filled_prompt: string;
  template: TemplateView;
  related: ImageView[];
};

export function buildNanoExampleHref(params: {
  locale: string;
  slug: string;
  exampleId: string;
}) {
  return `/${params.locale}/nano-template/${params.slug}/example/${encodeURIComponent(
    params.exampleId
  )}`;
}

export function buildNanoExampleHrefFromTemplateId(params: {
  locale: string;
  templateId: string;
  exampleId: string;
}) {
  return buildNanoExampleHref({
    locale: params.locale,
    slug: toSlug(params.templateId),
    exampleId: params.exampleId,
  });
}

export function getImageViewsForTemplate(
  reg: NanoRegistry,
  templateId: string,
  locale: PageLocale
): ImageView[] {
  const imgs = reg.imagesByTemplateId.get(templateId) ?? [];
  const rankScore = reg.templates.find((t) => t.id === templateId)?.rank_score;

  return imgs.map((img) => {
    const loc =
      img.locales?.[locale] ?? img.locales?.zh ?? img.locales?.en ?? {};

    const imageUrl = img.asset.image_url;
    const previewUrl = img.asset.preview_image_url ?? img.asset.image_url;

    return {
      id: img.id,
      template_id: img.template_id,
      locale,
      title: loc.title,
      category: loc.category,
      params: img.params ?? {},
      image_url: imageUrl,
      preview_image_url: previewUrl,
      audio_url: img.asset.audio_url,
      video_url: img.asset.video_url,
      rank_score: rankScore,
    };
  });
}

export function getCircularNeighbors<T extends { id: string }>(
  items: T[],
  currentId: string
): CircularNeighbors<T> | null {
  if (!items.length) return null;

  const index = items.findIndex((item) => item.id === currentId);
  if (index === -1) return null;

  return {
    prev: items[(index - 1 + items.length) % items.length],
    current: items[index],
    next: items[(index + 1) % items.length],
    index,
    total: items.length,
  };
}

export function getCircularImageViewNeighbors(
  reg: NanoRegistry,
  templateId: string,
  locale: PageLocale,
  currentId: string
): CircularNeighbors<ImageView> | null {
  const views = getImageViewsForTemplate(reg, templateId, locale);
  return getCircularNeighbors(views, currentId);
}

export function getNanoExamplesByTemplateId(
  templateId: string
): RawNanoImageRecord[] {
  return nanoRegistry.imagesByTemplateId.get(templateId) ?? [];
}

export function getNanoExampleById(
  templateId: string,
  imageId: string,
  locale: PageLocale = "en",
  translate?: TranslateFn
): NanoExampleDetail | null {
  const img = nanoRegistry.imageById.get(imageId);
  if (!img || img.template_id !== templateId) return null;

  const tv = translate
    ? getTemplateViewWithTranslations(nanoRegistry, templateId, locale, translate)
    : getTemplateView(nanoRegistry, templateId, locale);

  const base_prompt = tv?.base_prompt ?? "";
  const filled_prompt = fillPrompt(base_prompt, img.params ?? {});

  return { ...img, base_prompt, filled_prompt };
}

export function getNanoExampleDetail(
  reg: NanoRegistry,
  templateId: string,
  imageId: string,
  locale: PageLocale,
  translate?: TranslateFn
): NanoExampleDetailData | null {
  const raw = reg.imageById.get(imageId);
  if (!raw || raw.template_id !== templateId) return null;

  const template = translate
    ? getTemplateViewWithTranslations(reg, templateId, locale, translate)
    : getTemplateView(reg, templateId, locale);
  if (!template) return null;

  const loc = raw.locales?.[locale] ?? raw.locales?.zh ?? raw.locales?.en ?? {};

  const image: ImageView = {
    id: raw.id,
    template_id: raw.template_id,
    locale,
    title: loc.title,
    category: loc.category,
    params: raw.params ?? {},
    image_url: raw.asset.image_url,
    preview_image_url: raw.asset.preview_image_url ?? raw.asset.image_url,
    audio_url: raw.asset.audio_url,
    video_url: raw.asset.video_url,
  };

  const filled_prompt = fillPrompt(template.base_prompt, raw.params);

  const related = getImageViewsForTemplate(reg, templateId, locale)
    .filter((x) => x.id !== imageId)
    .slice(0, 6);

  return { image, filled_prompt, template, related };
}

export function buildCircularExampleNav(params: {
  reg: NanoRegistry;
  templateId: string;
  contentLocale: PageLocale;
  pageLocale: string;
  slug: string;
  currentExampleId: string;
}) {
  const neighbors = getCircularImageViewNeighbors(
    params.reg,
    params.templateId,
    params.contentLocale,
    params.currentExampleId
  );

  if (!neighbors || neighbors.total <= 1) return null;

  return {
    prev: {
      ...neighbors.prev,
      href: buildNanoExampleHref({
        locale: params.pageLocale,
        slug: params.slug,
        exampleId: neighbors.prev.id,
      }),
    },
    next: {
      ...neighbors.next,
      href: buildNanoExampleHref({
        locale: params.pageLocale,
        slug: params.slug,
        exampleId: neighbors.next.id,
      }),
    },
    index: neighbors.index,
    total: neighbors.total,
  };
}

/**
 * Returns up to `limit` examples most similar to the given example by
 * shared-signal overlap. Signals = inspiration tags ∪ inspiration topics
 * ∪ parent-template topics, so an inspiration with no tags/topics of
 * its own (common after an auto-tag pipeline run that did not enrich
 * it) still finds neighbors through its template's topic membership.
 * Same-template examples get a +2 bonus on top of signal overlap.
 * Caps at `maxPerTemplate` per template for cross-template diversity.
 */
export function getSimilarExamples(
  reg: NanoRegistry,
  currentId: string,
  opts?: { limit?: number; maxPerTemplate?: number }
): RawNanoImageRecord[] {
  const limit = opts?.limit ?? 12;
  const maxPerTemplate = opts?.maxPerTemplate ?? 4;

  const current = reg.imageById.get(currentId);
  if (!current) return [];

  const currentTemplate = reg.templateById.get(current.template_id);
  const currentSignals = new Set<string>([
    ...(current.tags ?? []),
    ...(current.topics ?? []),
    ...(currentTemplate ? getTemplateTopics(currentTemplate) : []),
  ]);
  if (currentSignals.size === 0) return [];

  // Cache per-template topics so the candidate loop doesn't redo the
  // normalize/dedupe work for every image in a multi-image template.
  const templateTopicsCache = new Map<string, string[]>();
  const topicsFor = (templateId: string): string[] => {
    const cached = templateTopicsCache.get(templateId);
    if (cached) return cached;
    const tpl = reg.templateById.get(templateId);
    const t = tpl ? getTemplateTopics(tpl) : [];
    templateTopicsCache.set(templateId, t);
    return t;
  };

  const scored = reg.images
    .filter((img) => img.id !== currentId && img.asset?.image_url)
    .map((img) => {
      let signalScore = 0;
      const seen = new Set<string>();
      for (const sig of [
        ...(img.tags ?? []),
        ...(img.topics ?? []),
        ...topicsFor(img.template_id),
      ]) {
        if (seen.has(sig)) continue;
        seen.add(sig);
        if (currentSignals.has(sig)) signalScore++;
      }
      const sameTemplate = img.template_id === current.template_id ? 2 : 0;
      return { img, score: signalScore + sameTemplate };
    })
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score);

  const perTemplateCount: Record<string, number> = {};
  const results: RawNanoImageRecord[] = [];

  for (const { img } of scored) {
    if (results.length >= limit) break;
    const count = perTemplateCount[img.template_id] ?? 0;
    if (count >= maxPerTemplate) continue;
    perTemplateCount[img.template_id] = count + 1;
    results.push(img);
  }

  return results;
}