#!/usr/bin/env node
/**
 * build_review_checklist.cjs
 * ---------------------------------------------------------------------------
 * Generate docs/vir-routing-eval-v1-review-checklist.md from the CURRENT
 * vir_routing_gold.json (+ the eval notes it was drafted against).
 *
 * The gold in vir_routing_gold.json is a Claude draft pending human sign-off.
 * This turns the 44KB JSON into a decision-only checklist: every row is a
 * yes/no the reviewer can rule on without re-reading the raw file.
 *
 * Categories surfaced (all derived from data, no hand-curation):
 *   1. Content-gap calls        acceptable=[]  (ranked by conflict w/ eval note)
 *   2. Capability overrides     gold primary not named in the eval note
 *   3. Subject-gate drops       eval-note-named template demoted to near_miss
 *   4. Cross-query consistency  a near_miss here that is ACCEPTED elsewhere
 *
 * Pure over local JSON. Re-runnable: node scripts/build_review_checklist.cjs
 */
const fs = require('fs');
const path = require('path');

const CFG = path.join(__dirname, 'configs');
const gold = require(path.join(CFG, 'vir_routing_gold.json')).queries;
const evalArr = require(path.join(CFG, 'search_eval_set.json')).queries;
const kb = require(path.join(CFG, 'template_capability_kb.json'));
const OUT = path.join(__dirname, '..', 'docs', 'vir-routing-eval-v1-review-checklist.md');

const strip = (s) => (s || '').replace(/^template-/, '');
const evalByQ = {};
evalArr.forEach((x) => (evalByQ[x.query] = x));

// --- KB template id set (for note-token matching) ------------------------
const kbArr = Array.isArray(kb) ? kb : kb.templates || Object.values(kb);
const allIds = new Set();
kbArr.forEach((t) => {
  const id = t.template_id || t.id || t.templateId;
  if (id) allIds.add(strip(id));
});
function noteNamedIds(note) {
  if (!note) return [];
  const low = note.toLowerCase();
  const found = [];
  allIds.forEach((id) => {
    if (low.includes(id)) found.push(id);
  });
  return found;
}

// --- where is each template accepted / primary? (consistency index) ------
const acceptedIn = {};
const primaryIn = {};
gold.forEach((x) => {
  (x.acceptable_template_ids || []).forEach((id) => {
    (acceptedIn[strip(id)] = acceptedIn[strip(id)] || []).push(x.query);
  });
  if (x.primary_template_id) {
    (primaryIn[strip(x.primary_template_id)] = primaryIn[strip(x.primary_template_id)] || []).push(x.query);
  }
});

// --- classify rows -------------------------------------------------------
const gaps = [];
const overrides = [];
const drops = [];
const consistency = [];

gold.forEach((x) => {
  const note = evalByQ[x.query];
  const noteIds = note ? noteNamedIds(note.notes) : [];
  const acc = (x.acceptable_template_ids || []).map(strip);
  const nm = (x.near_miss_template_ids || []).map(strip);
  const prim = x.primary_template_id ? strip(x.primary_template_id) : null;

  // 1. content gap
  if (acc.length === 0) {
    gaps.push({ x, note, noteIds });
  }

  // 2. capability override: gold primary not mentioned anywhere in note text,
  //    while the note DID name other template ids
  if (prim && noteIds.length > 0 && !(note && note.notes.toLowerCase().includes(prim))) {
    overrides.push({ x, note, prim, noteIds });
  }

  // 3. subject-gate drop: note named it, gold demoted to near_miss (not acc)
  const dropped = noteIds.filter((id) => nm.includes(id) && !acc.includes(id));
  if (dropped.length) drops.push({ x, note, dropped });

  // 4. consistency: a near_miss here that is accepted in some OTHER query
  (nm).forEach((id) => {
    const others = (acceptedIn[id] || []).filter((q) => q !== x.query);
    if (others.length) consistency.push({ query: x.query, gap: acc.length === 0, id, others });
  });
});

// conflict severity for gaps: note said content exists but gold says none
const sev = { moderate: 3, rich: 3, thin: 1, empty: 0, '?': 0 };
gaps.sort((a, b) => {
  const sa = Math.max(sev[a.note ? a.note.expected_templates : '?'] || 0, 0);
  const sb = Math.max(sev[b.note ? b.note.expected_templates : '?'] || 0, 0);
  return sb - sa;
});

// --- render --------------------------------------------------------------
const L = [];
const p = (s = '') => L.push(s);
const box = () => '- [ ] ';
const fmtList = (a) => (a && a.length ? a.map((t) => `\`${t}\``).join(', ') : '_(none)_');

p('# VIR Routing Gold — Human Review Checklist (v1)');
p('');
p('**Generated by** `scripts/build_review_checklist.cjs` from `scripts/configs/vir_routing_gold.json` — re-run after any gold edit.');
p(`**Gold under review:** ${gold.length} queries. **Status:** Claude draft, pending human sign-off.`);
p('');
p('> This is the gate for the whole eval. Until the gold is signed off, any "KB lift" number is contaminated (the gold was drafted reading the KB). Rule on each row below, then flip `review_status` in the gold JSON.');
p('');
p('**How to use.** Each row is one decision. Check the box when resolved. Mark the verdict inline:');
p('- ✅ **keep** — Claude\'s call is right, no change');
p('- ✏️ **change** — edit the gold (note what to change: promote/demote/add/remove which id)');
p('- ❓ **discuss** — needs a second opinion');
p('');
p('---');
p('');

// SECTION 1
p(`## 1. Content-gap calls — \`acceptable_template_ids = []\` (${gaps.length})`);
p('');
p('Does this query genuinely have **no honest route**, or did the router miss one? Rows are ordered by conflict severity: top rows are where the eval note expected real content (`moderate`/`rich`) but the gold says "gap" — the sharpest disagreements.');
p('');
gaps.forEach(({ x, note, noteIds }) => {
  const et = note ? note.expected_templates : '?';
  const conflict = (sev[et] || 0) >= 3 ? ' ⚠️ **CONFLICT**' : '';
  p(`### ${box()}\`${x.query}\`  _(${x.locale}, ${x.ambiguity})_${conflict}`);
  p(`- **eval note:** expected=\`${note ? note.expected : '?'}\` · expected_templates=\`${et}\``);
  if (note && note.notes) p(`- **note text:** ${note.notes}`);
  p(`- **near-misses the router saw:** ${fmtList(x.near_miss_template_ids.map(strip))}`);
  if (x.rationale) p(`- **Claude rationale:** ${x.rationale}`);
  p(`- **Decision:** is this a true content gap, or should one of the near-misses be promoted to acceptable? → _____`);
  p('');
});
p('---');
p('');

// SECTION 2
p(`## 2. Capability-driven overrides — gold primary not named in the eval note (${overrides.length})`);
p('');
p('Here the gold\'s `primary_template_id` was chosen from **mined example evidence** (what the template can actually generate), over the template(s) the human eval note named. Verify the evidence justifies overriding the note.');
p('');
overrides.forEach(({ x, note, prim, noteIds }) => {
  p(`### ${box()}\`${x.query}\`  _(${x.locale}, ${x.ambiguity})_`);
  p(`- **gold primary:** \`${prim}\`  ·  **note named instead:** ${fmtList(noteIds)}`);
  p(`- **note text:** ${note && note.notes ? note.notes : '_(none)_'}`);
  if (x.evidence) p(`- **KB evidence:** ${x.evidence}`);
  if (x.rationale) p(`- **Claude rationale:** ${x.rationale}`);
  p(`- **Decision:** does the example evidence justify overriding the note? → _____`);
  p('');
});
p('---');
p('');

// SECTION 3
p(`## 3. Subject-gate drops — note-named template demoted to near_miss (${drops.length})`);
p('');
p('The eval note named these templates, but the gold pushed them to `near_miss_template_ids` on a **subject mismatch** (right layout, wrong subject). Confirm each demotion is correct and not a lost valid route.');
p('');
drops.forEach(({ x, note, dropped }) => {
  p(`### ${box()}\`${x.query}\`  _(${x.locale}, ${x.ambiguity})_`);
  p(`- **demoted to near_miss:** ${fmtList(dropped)}`);
  p(`- **kept as acceptable:** ${fmtList(x.acceptable_template_ids.map(strip))}`);
  if (x.rationale) p(`- **Claude rationale:** ${x.rationale}`);
  p(`- **Decision:** correct subject-gate drop, or should any be restored to acceptable? → _____`);
  p('');
});
p('---');
p('');

// SECTION 4
p(`## 4. Cross-query consistency flags (${consistency.length})`);
p('');
p('Each row: a template the gold treats as a **near_miss (rejected) here**, but **accepts in another query**. Either the two queries genuinely differ, or one verdict is wrong. Gap-query rows (marked 🚩) are the most suspect — we called it a content gap while accepting the same template elsewhere.');
p('');
p('| ✓ | query | near_miss (rejected here) | but ACCEPTED in | note |');
p('|---|---|---|---|---|');
consistency
  .sort((a, b) => (b.gap ? 1 : 0) - (a.gap ? 1 : 0))
  .forEach((c) => {
    const flag = c.gap ? '🚩 gap-query' : '';
    p(`| [ ] | \`${c.query}\` | \`${c.id}\` | ${c.others.map((q) => `\`${q}\``).join(', ')} | ${flag} |`);
  });
p('');
p('---');
p('');

// SIGN-OFF
p('## Sign-off');
p('');
p('| Section | Rows | Resolved |');
p('|---|---|---|');
p(`| 1 · Content-gap calls | ${gaps.length} | ☐ |`);
p(`| 2 · Capability overrides | ${overrides.length} | ☐ |`);
p(`| 3 · Subject-gate drops | ${drops.length} | ☐ |`);
p(`| 4 · Consistency flags | ${consistency.length} | ☐ |`);
p('');
p('When all four are resolved and the gold JSON is edited accordingly:');
p('1. Re-run `node scripts/validate_gold.cjs` (must be 0 errors).');
p('2. Set `review_status: "human-reviewed"` in `vir_routing_gold.json`.');
p('3. Re-run `node scripts/build_review_checklist.cjs` — a clean re-run confirms nothing new regressed.');
p('4. Only then quantify KB lift (§4b of the summary) — the gold is now uncontaminated.');
p('');

fs.writeFileSync(OUT, L.join('\n'));
console.log(
  `Wrote ${OUT}\n  content-gaps: ${gaps.length}\n  overrides:    ${overrides.length}\n  drops:        ${drops.length}\n  consistency:  ${consistency.length}`
);
