#!/usr/bin/env python3
"""Batch 3 topic enrichment: comic, character-ip, merch, mood-board, mascots,
ecommerce, industrial-design. Upgrades stubs/creates missing entries to FULL
(displayName/title/description/intro/keywords) + adds a `format` rich body.
Injects into messages/{en,zh}/topics.json. Idempotent."""
import json, sys

# base: only set fields that are missing (never clobber an existing displayName/title)
BASE_EN = {
 "comic": {"displayName":"Comics","title":"Comic & Manga Prompts, Templates and Inspiration","description":"Create comic strips, manga pages, and character intros with AI — multi-panel layouts, expressive art, and story beats, no drawing skills needed.","intro":"Explore AI comic and manga templates for turning a character, joke, or story into finished panels. Whether you're making a meme strip, a manga-style page, a character intro spread, or a short visual story, these templates handle the layout, paneling, and art style so you can focus on the story.","keywords":["manga","comic strip","webtoon"]},
 "character-ip": {"displayName":"Character Design","title":"Character Design & IP Prompts, Templates and Inspiration","description":"Design original characters and IP with AI — model sheets, turnarounds, expression sheets, mascots, and merch-ready poses, all consistent across the set.","intro":"Explore AI character-design and IP templates for building an original character from scratch or expanding one into a full asset set. From model sheets and turnarounds to expression sheets, sticker poses, and merch mockups, these templates keep the character consistent across every output.","keywords":["character sheet","original character","IP design","mascot"]},
 "mood-board": {"displayName":"Mood Boards","title":"Mood Board Prompts, Templates and Inspiration","description":"Create mood boards and visual-direction boards with AI — colors, textures, type, and imagery pulled into one cohesive aesthetic for a brand, product, or project.","intro":"Explore AI mood-board templates for pinning down a look before you build. Describe a brand, product, or vibe and get a cohesive board of colors, textures, typography, and reference imagery — the first step of any design or branding project, generated in seconds.","keywords":["moodboard","visual direction","aesthetic board","brand mood"]},
 "mascots": {"displayName":"Mascots","title":"Mascot Design Prompts, Templates and Inspiration","description":"Design brand and character mascots with AI — a friendly, ownable character in consistent poses, ready for stickers, merch, and applications.","intro":"Explore AI mascot-design templates for giving a brand, team, or product a memorable face. Describe the personality and get a mascot rendered in a consistent style across poses and expressions — ready to turn into stickers, merch, and brand applications.","keywords":["mascot design","brand character","kawaii mascot"]},
 "industrial-design": {"displayName":"Industrial Design","title":"Industrial Design Prompts, Templates and Inspiration","description":"Create industrial-design concepts with AI — product concept boards, presentation sheets, and concept sketches that make an idea look designed and buildable.","intro":"Explore AI industrial-design templates for turning a product idea into a designed concept. From concept sketches and presentation boards to spec-style layouts, these templates render a product with materials, form, and context so a concept looks studio-made — useful for pitches, decks, and factory briefs.","keywords":["product design","concept board","product concept","design sketch"]},
}
FORMAT_EN = {
 "comic": {"lead":"Comics and manga turn a story or joke into sequential panels with expressive characters. Curify lays out the panels, art, and flow from your idea — no drawing required.","howToTitle":"How to make a comic","howTo":["Pick a comic or manga template.","Describe your characters and the story beats or punchline.","Generate a finished multi-panel page.","Download to share or print, or tweak and regenerate."],"usesTitle":"What you can make","uses":["Multi-panel comic strips","Manga-style pages","Character intro spreads","Meme and joke comics","Short visual stories"],"faqTitle":"Comic FAQ","faq":[{"q":"Do I need to draw?","a":"No. You provide the characters and story; Curify handles the paneling, art, and lettering."},{"q":"Can I keep a character consistent across panels?","a":"Yes — templates hold one character's look across the panels of a page."},{"q":"Can I print the comic?","a":"Yes, pages export at high resolution for sharing or print."}]},
 "character-ip": {"lead":"Character design turns an idea into an ownable character — with a consistent model, expressions, and poses you can reuse across stickers, comics, and merch. Curify generates the whole set from one description or reference.","howToTitle":"How to design a character","howTo":["Pick a character-design template — model sheet, turnaround, or expression set.","Describe your character, or upload a reference to base it on.","Generate a consistent set of views and poses.","Reuse the character across stickers, comics, and merch."],"usesTitle":"What you can make","uses":["Character model sheets and turnarounds","Expression and pose sheets","Original character (OC) and IP designs","Mascot and sticker-ready poses","Merch and product mockups of the character"],"faqTitle":"Character design FAQ","faq":[{"q":"Can I keep the character consistent across outputs?","a":"Yes — that's the point: templates hold one character model across poses, expressions, and applications."},{"q":"Can I base a character on my own art or photo?","a":"Yes, several templates let you upload a reference so the set is built from your design."},{"q":"Can I use the character commercially?","a":"Outputs are built for IP and merch use — stickers, print-on-demand, and brand applications."}]},
 "merch": {"lead":"Merch turns a character, brand, or idea into sellable goods — sticker packs, apparel, gift boxes, and full product families. Curify renders professional merch mockups and product art from your concept.","howToTitle":"How to make merch","howTo":["Pick a merch template — sticker pack, apparel, gift box, or full set.","Describe the character or brand, or upload your design.","Generate a realistic merch mockup or product sheet.","Download for your store, listing, or factory brief."],"usesTitle":"What you can make","uses":["Sticker packs and die-cut sheets","Apparel and accessory mockups","Gift boxes and stationery sets","IP and character goods","Full SKU / product-family sheets"],"faqTitle":"Merch FAQ","faq":[{"q":"Is this ready for print-on-demand?","a":"Yes — many templates output print-ready, die-cut-ready, or listing-ready assets for POD and marketplaces like Etsy."},{"q":"Can I put my own character or logo on it?","a":"Yes, several templates let you upload your artwork so it appears on the product."},{"q":"Can I make a whole product line?","a":"Yes — build a consistent set of goods around one character or brand."}]},
 "mood-board": {"lead":"Mood boards pin down a look before you build — colors, textures, type, and imagery in one cohesive aesthetic. Curify explores a mood board for a brand, product, or vibe from your brief.","howToTitle":"How to make a mood board","howTo":["Pick a mood-board template.","Describe the brand, product, or feeling you're after.","Generate a cohesive board of colors, textures, and imagery.","Refine the direction and regenerate, or apply it to designs."],"usesTitle":"What you can make","uses":["Brand and product mood boards","Aesthetic and vibe direction","Color and texture exploration","Interior and fashion mood boards","Pitch and concept boards"],"faqTitle":"Mood board FAQ","faq":[{"q":"Do I need design skills?","a":"No. Describe the feeling and Curify assembles a coherent board of colors, textures, and reference imagery."},{"q":"Can I use it for a client pitch?","a":"Yes — boards are built to present a clear visual direction."},{"q":"Can I turn the direction into designs?","a":"Yes — use the board's palette and mood as the brief for logos, packaging, or product mockups."}]},
 "mascots": {"lead":"Mascots give a brand, team, or product a memorable, ownable face. Curify designs a mascot in a consistent style across poses and expressions, ready for stickers, merch, and applications.","howToTitle":"How to design a mascot","howTo":["Pick a mascot-design template.","Describe the personality, brand, and style.","Generate a mascot in consistent poses and expressions.","Turn it into stickers, merch, or brand applications."],"usesTitle":"What you can make","uses":["Brand and team mascots","Kawaii and chibi characters","Mascot pose and expression sheets","Sticker and emoji sets","Merch and packaging applications"],"faqTitle":"Mascot FAQ","faq":[{"q":"Can I keep the mascot consistent?","a":"Yes — templates hold one mascot model across poses and expressions so the set looks unified."},{"q":"Can I base it on my brand?","a":"Yes — describe the brand and style, or upload a reference, and the mascot is built around it."},{"q":"Can I use it on products?","a":"Yes — mascots are built to apply to stickers, merch, and packaging."}]},
 "ecommerce": {"lead":"Ecommerce visuals make a product look professional and listing-ready — clean product shots, lifestyle scenes, and six-grid detail images. Curify renders them from your product or description.","howToTitle":"How to make ecommerce images","howTo":["Pick an ecommerce template — product shot, lifestyle, or detail grid.","Describe the product, or upload your product image.","Generate a professional, listing-ready visual.","Download for Amazon, Shopify, or your store."],"usesTitle":"What you can make","uses":["Clean product listing images","Lifestyle and in-context shots","Six-grid product detail infographics","Promotional and ad creatives","Brand and packaging mockups"],"faqTitle":"Ecommerce FAQ","faq":[{"q":"Can I use my own product photo?","a":"Yes — several templates let you upload your product so the scene is built around it."},{"q":"Are these good for Amazon / Shopify listings?","a":"Yes, they're formatted to look like professional listing and detail images."},{"q":"Do I need a photographer?","a":"No. Curify renders the product, lighting, and setting from a description or your photo."}]},
 "industrial-design": {"lead":"Industrial design turns a product idea into a designed, buildable concept — concept sketches, presentation boards, and spec-style layouts. Curify renders it with materials, form, and context from your brief.","howToTitle":"How to make an industrial-design concept","howTo":["Pick an industrial-design template — concept sketch or presentation board.","Describe the product, materials, and use case.","Generate a studio-quality concept with form and context.","Download for your pitch deck, portfolio, or factory brief."],"usesTitle":"What you can make","uses":["Product concept boards","Concept and ideation sketches","Presentation and spec-style layouts","Material and finish exploration","Pitch and portfolio visuals"],"faqTitle":"Industrial design FAQ","faq":[{"q":"Do I need CAD or 3D software?","a":"No. Curify renders the product concept, materials, and context from a description."},{"q":"Is this a final production design?","a":"It's a concept and presentation — a designed direction to align on and iterate, not a manufacturing file."},{"q":"Can I present it to a client or factory?","a":"Yes — the boards are built to look like a professional design presentation."}]},
}

BASE_ZH = {
 "comic": {"displayName":"漫画","title":"漫画与 Manga 提示词、模板与灵感","description":"用 AI 制作四格漫画、Manga 分页与角色介绍——多格版式、生动画风与故事节奏，无需绘画基础。","intro":"探索 AI 漫画与 Manga 模板，把一个角色、笑点或故事变成成品分格。无论是梗图连环画、Manga 风分页、角色介绍跨页，还是短篇视觉故事，模板都会为你处理版式、分格与画风，让你专注于故事本身。","keywords":["manga","连环画","条漫"]},
 "character-ip": {"displayName":"角色设计","title":"角色设计与 IP 提示词、模板与灵感","description":"用 AI 设计原创角色与 IP——设定图、三视图、表情表、吉祥物与可做周边的姿势，整套风格统一。","intro":"探索 AI 角色设计与 IP 模板，从零打造一个原创角色，或把它扩展成完整资产集。从设定图、三视图到表情表、贴纸姿势与周边样机，模板让角色在每一张输出中都保持一致。","keywords":["角色设定图","原创角色","IP 设计","吉祥物"]},
 "mood-board": {"displayName":"情绪板","title":"情绪板提示词、模板与灵感","description":"用 AI 制作情绪板与视觉方向板——把配色、材质、字体与图像汇聚成一套统一的调性，用于品牌、产品或项目。","intro":"探索 AI 情绪板模板，在动手之前先定下调性。描述一个品牌、产品或氛围，即可得到一块由配色、材质、字体与参考图像组成的统一板面——任何设计或品牌项目的第一步，几秒生成。","keywords":["情绪板","视觉方向","美学板","品牌调性"]},
 "mascots": {"displayName":"吉祥物","title":"吉祥物设计提示词、模板与灵感","description":"用 AI 设计品牌与角色吉祥物——一个亲切、可拥有的角色，姿势统一，可用于贴纸、周边与应用。","intro":"探索 AI 吉祥物设计模板，为品牌、团队或产品打造一张令人记住的面孔。描述性格，即可得到风格统一、多姿势多表情的吉祥物——可直接做成贴纸、周边与品牌应用。","keywords":["吉祥物设计","品牌角色","可爱吉祥物"]},
 "industrial-design": {"displayName":"工业设计","title":"工业设计提示词、模板与灵感","description":"用 AI 制作工业设计概念——产品概念板、呈现图与概念草图，让创意看起来经过设计、可被制造。","intro":"探索 AI 工业设计模板，把一个产品创意变成经过设计的概念。从概念草图、呈现板到规格式版面，模板会带材质、形态与场景地渲染产品，让概念看起来出自工作室——适用于路演、演示与工厂简报。","keywords":["产品设计","概念板","产品概念","设计草图"]},
}
FORMAT_ZH = {
 "comic": {"lead":"漫画与 Manga 把故事或笑点变成一格格连贯、角色生动的分格。Curify 会根据你的想法排布分格、画风与叙事流程——无需绘画。","howToTitle":"如何制作漫画","howTo":["选择漫画或 Manga 模板。","描述你的角色以及故事节奏或笑点。","生成成品多格分页。","下载分享或打印，或调整后重新生成。"],"usesTitle":"你可以做什么","uses":["多格四格漫画","Manga 风分页","角色介绍跨页","梗图与笑点漫画","短篇视觉故事"],"faqTitle":"漫画常见问题","faq":[{"q":"需要会画画吗？","a":"不需要。你提供角色和故事，Curify 负责分格、画风与对白。"},{"q":"能让角色在各格之间保持一致吗？","a":"可以——模板会在一页的各格之间保持同一角色的形象。"},{"q":"漫画可以打印吗？","a":"可以，分页以高分辨率导出，可供分享或打印。"}]},
 "character-ip": {"lead":"角色设计把一个创意变成可拥有的角色——形象、表情与姿势统一，可复用于贴纸、漫画与周边。Curify 会根据一段描述或参考图生成整套。","howToTitle":"如何设计角色","howTo":["选择角色设计模板——设定图、三视图或表情集。","描述你的角色，或上传参考图作为基础。","生成一整套一致的视角与姿势。","把角色复用到贴纸、漫画与周边上。"],"usesTitle":"你可以做什么","uses":["角色设定图与三视图","表情与姿势表","原创角色（OC）与 IP 设计","吉祥物与可做贴纸的姿势","角色周边与产品样机"],"faqTitle":"角色设计常见问题","faq":[{"q":"能让角色在各输出间保持一致吗？","a":"可以，这正是重点：模板会在姿势、表情与应用间保持同一角色形象。"},{"q":"可以基于我自己的画作或照片吗？","a":"可以，多个模板支持上传参考图，让整套基于你的设计。"},{"q":"可以商用吗？","a":"输出专为 IP 与周边使用而设计——贴纸、按需印刷与品牌应用。"}]},
 "merch": {"lead":"周边把一个角色、品牌或创意变成可售卖的商品——贴纸包、服装、礼盒与完整产品家族。Curify 会根据你的概念渲染专业的周边样机与产品图。","howToTitle":"如何制作周边","howTo":["选择周边模板——贴纸包、服装、礼盒或整套。","描述角色或品牌，或上传你的设计。","生成逼真的周边样机或产品图。","下载用于店铺、详情页或工厂简报。"],"usesTitle":"你可以做什么","uses":["贴纸包与刀模贴纸","服装与配件样机","礼盒与文具套装","IP 与角色商品","完整 SKU / 产品家族图"],"faqTitle":"周边常见问题","faq":[{"q":"适合按需印刷吗？","a":"适合——许多模板输出可印刷、可刀模或可上架的素材，适配 POD 与 Etsy 等平台。"},{"q":"可以放上我自己的角色或 logo 吗？","a":"可以，多个模板支持上传作品，让它出现在产品上。"},{"q":"可以做一整条产品线吗？","a":"可以——围绕一个角色或品牌打造风格统一的一套商品。"}]},
 "mood-board": {"lead":"情绪板在动手之前先定下调性——把配色、材质、字体与图像汇成一套统一的美学。Curify 会根据你的简报为品牌、产品或氛围探索一块情绪板。","howToTitle":"如何制作情绪板","howTo":["选择情绪板模板。","描述你想要的品牌、产品或感觉。","生成一块由配色、材质与图像组成的统一板面。","调整方向后重新生成，或应用到设计上。"],"usesTitle":"你可以做什么","uses":["品牌与产品情绪板","美学与氛围方向","配色与材质探索","室内与时尚情绪板","提案与概念板"],"faqTitle":"情绪板常见问题","faq":[{"q":"需要设计基础吗？","a":"不需要。描述感觉，Curify 会拼出一块由配色、材质与参考图像组成的连贯板面。"},{"q":"可以用于客户提案吗？","a":"可以——板面专为清晰呈现视觉方向而设计。"},{"q":"可以把方向变成设计吗？","a":"可以——把板面的配色与调性作为 logo、包装或产品样机的简报。"}]},
 "mascots": {"lead":"吉祥物给品牌、团队或产品一张令人记住、可拥有的面孔。Curify 设计风格统一、多姿势多表情的吉祥物，可直接用于贴纸、周边与应用。","howToTitle":"如何设计吉祥物","howTo":["选择吉祥物设计模板。","描述性格、品牌与风格。","生成姿势与表情统一的吉祥物。","把它做成贴纸、周边或品牌应用。"],"usesTitle":"你可以做什么","uses":["品牌与团队吉祥物","可爱与 Q 版角色","吉祥物姿势与表情表","贴纸与表情套装","周边与包装应用"],"faqTitle":"吉祥物常见问题","faq":[{"q":"能让吉祥物保持一致吗？","a":"可以——模板会在多姿势多表情间保持同一吉祥物形象，整套统一。"},{"q":"可以基于我的品牌吗？","a":"可以——描述品牌与风格，或上传参考图，吉祥物即围绕它打造。"},{"q":"可以用在产品上吗？","a":"可以——吉祥物专为应用到贴纸、周边与包装而设计。"}]},
 "ecommerce": {"lead":"电商视觉让产品看起来专业、可直接上架——干净的产品图、生活场景图与六宫格细节图。Curify 会根据你的产品或描述渲染它们。","howToTitle":"如何制作电商图片","howTo":["选择电商模板——产品图、生活场景或细节网格。","描述产品，或上传你的产品图。","生成专业、可上架的视觉。","下载用于亚马逊、Shopify 或你的店铺。"],"usesTitle":"你可以做什么","uses":["干净的产品详情图","生活化与情景图","六宫格产品细节信息图","促销与广告素材","品牌与包装样机"],"faqTitle":"电商常见问题","faq":[{"q":"可以用我自己的产品照片吗？","a":"可以——多个模板支持上传产品，让场景围绕它构建。"},{"q":"适合亚马逊 / Shopify 详情页吗？","a":"适合，它们按专业上架图与细节图的样式排布。"},{"q":"需要摄影师吗？","a":"不需要。Curify 会根据描述或你的照片渲染产品、光影与场景。"}]},
 "industrial-design": {"lead":"工业设计把产品创意变成经过设计、可制造的概念——概念草图、呈现板与规格式版面。Curify 会根据简报带材质、形态与场景渲染。","howToTitle":"如何制作工业设计概念","howTo":["选择工业设计模板——概念草图或呈现板。","描述产品、材质与使用场景。","生成带形态与场景的工作室级概念。","下载用于路演、作品集或工厂简报。"],"usesTitle":"你可以做什么","uses":["产品概念板","概念与创意草图","呈现与规格式版面","材质与工艺探索","路演与作品集视觉"],"faqTitle":"工业设计常见问题","faq":[{"q":"需要 CAD 或 3D 软件吗？","a":"不需要。Curify 会根据描述渲染产品概念、材质与场景。"},{"q":"这是最终量产设计吗？","a":"这是概念与呈现——用于统一共识和迭代的设计方向，而非制造文件。"},{"q":"可以拿给客户或工厂看吗？","a":"可以——这些板专为呈现专业的设计提案而设计。"}]},
}

def inject(path, base, fmt):
    d=json.load(open(path,encoding='utf-8')); topics=d['topics']; n=0
    allslugs=set(list(base.keys())+list(fmt.keys()))
    for slug in allslugs:
        e=topics.setdefault(slug,{})
        for k,v in (base.get(slug) or {}).items():
            e.setdefault(k,v)  # never clobber existing base fields
        if slug in fmt: e['format']=fmt[slug]
        n+=1
    open(path,'w',encoding='utf-8').write(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
    print(f'  {path}: {n} topics')

base=sys.argv[1]
inject(f'{base}/messages/en/topics.json', BASE_EN, FORMAT_EN)
inject(f'{base}/messages/zh/topics.json', BASE_ZH, FORMAT_ZH)
