#!/usr/bin/env node
// scripts/build_blog_slugs.cjs
//
// Emits lib/blog-slugs.generated.ts — the set of real /blog/<slug> values.
//
// WHY a generated file rather than importing blogs.json directly: middleware
// runs on the edge and this set is needed there (see middleware.ts, the
// blog-404 gate). blogs.json is 151KB and blog-config.ts imports all of it;
// pulling either into the edge bundle to answer "does this slug exist" would
// ship the entire blog corpus to every request. The slug list is ~3KB.
//
// Usage:
//   node scripts/build_blog_slugs.cjs
//   node scripts/build_blog_slugs.cjs --check   # CI: fail if stale
"use strict";
const fs = require("fs");
const path = require("path");

const blogs = require(path.join(__dirname, "..", "public", "data", "blogs.json"));
const outPath = path.join(__dirname, "..", "lib", "blog-slugs.generated.ts");

const slugs = [...new Set(blogs.map((b) => b && b.slug).filter(Boolean))].sort();

const body = `// GENERATED by scripts/build_blog_slugs.cjs — do not edit by hand.
// Run \`node scripts/build_blog_slugs.cjs\` after changing public/data/blogs.json.
//
// Consumed by middleware.ts to return a real 404 for unknown /blog/* URLs.
// Kept separate from blog-config.ts on purpose: that module imports the whole
// 151KB blogs.json, which must not reach the edge bundle.

export const BLOG_SLUGS: ReadonlySet<string> = new Set([
${slugs.map((s) => `  ${JSON.stringify(s)},`).join("\n")}
]);
`;

if (process.argv.includes("--check")) {
  const cur = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : "";
  if (cur !== body) {
    console.error("lib/blog-slugs.generated.ts is STALE. Run: node scripts/build_blog_slugs.cjs");
    process.exit(1);
  }
  console.log(`ok — ${slugs.length} slugs, generated file is current`);
  process.exit(0);
}

fs.writeFileSync(outPath, body);
console.log(`wrote ${slugs.length} slugs → ${path.relative(process.cwd(), outPath)}`);
